let frases = [
    ["Solo sé que no se nada", "Sócrates"],
    ["Un pequeño paso para el hombre, un gran paso para la humanidad", "Neil Armstrong"],
    ["Tengo un sueño", "Martin Luther King"],
    ["si buscas resultados distintos, no hagas siempre lo mismo", "Albert Einstein"],
    ["Pienso, luego existo", "René descartes"],
    ["Aquellos que no conocen la historia están condenados a repetirla", "Edmun Burke"],
    ["Todos somos genios. Pero si juzgas a un pez por su capacidad de trepar árboles, vivirá toda su vida pensando que es un inútil", "Albert Einstein"],
    ["Dale pescado a un hombre y comerá un día. Enséñale a pescar y comerá toda la vida", "Lao Tsé"],
    ["Vive como si fueras a morir mañana. Aprende como si fueras a vivir siempre", "Mahatma Gandhi"],
    ["Nunca discutas con un estúpido, te hará descender a su nivel ahí te vencerá por experiencia", "Mark Twain"],
    ["Cáete siete veces, levántate ocho", "Provervio japonés"],
    ["Más vale morir de pie que vivir de rodillas", "Autor desconocido, posiblemente Emiliano Zapata"],
    ["No estarlo", "Nelson Mandela"],
    ["A pesar de todo, sigo pensando que la gente es buena", "Ana Frank"],
    ["La historia de los grandes acontecimientos del mundo apenas es más que la histores ser en el mundo", "Mahatma Gandhi"],
    ["Haz el amor y no la guerra", "Gershon Legman"],
    ["La mejor manera de evitar la tentación es caer en ella", "Oscar Wilde"],
    ["Nunca me he ender algo", "Galileo Galilei"],
    ["Solo hay dos cosas infinitas: el Universo y la estupidez humana, aunque de la primera no estoy seguro", "Albert\r\n    Einstein"],
    ["Vi el ángel el Angel"],
    ["Nunca te olvides de sonreír, porque el día que no sonrías será un día perdido", "Charlie Chaplin"],
    ["La medida del amor es amar sin medida", "San Agustín"],
    ["No hay, el tonto se fija en el dedo", "Confucio"],
    ["Podrán cortar las flores, pero no podrán detener la primavera", "Pablo Neruda"],
    ["A Dios pongo por testigo que jamás volveré a pasar hambre", "Lo que el viento se llevó"],
    ["Mi casa… Teléfono...", "E.T."],
    ["Que la Fuerza te acompañe", "Star Wars"],
    ["Siempre nos quedará París", "Casablanca"],
    ["Mi madre dice que la vida es como una caja de bombones, nunca sabes qué te va a tocar", "Forrest Gump"],
    ["Pueden quitarnos la vida, pero jamás nos quitarán… ¡La libertad!", "Braveheart"],
    ["¿Hablas conmigo? ¿Me lo dices a mí? Dime, ¿es a mí?", "Taxi Driver"],
    ["La primera regla del Club de la Lucha es: No hables del Club de la Lucha", "El Club de la Lucha"],
    ["No, yo soy tu padre", "Star Wars"],
    ["Sayonara, baby", "Terminator 2"],
    ["Solo existen dos cosas infinitas, el universo y la estupidez humana. Y del universo no estoy seguro", ["Albert Einstein"]]
]